version: '3.7'
services:

  app:
    image: node:18.4
    volumes:
      - ./src:/app/src:delegated
      - ./node_modules:/app/node_modules:delegated
      - ./package.json:/app/package.json:delegated
    working_dir: /app
    ports:
      - 8080:8080
    command:
      - npm
      - run
      - server

  api:
    image: node:18.4
    volumes:
      - ./src:/app/src:delegated
      - ./node_modules:/app/node_modules:delegated
    working_dir: /app
    ports:
      - 1234:1234
    command:
      - node
      - src/server.js

  varnish:
    image: varnish:6.0
    environment:
      - VARNISH_SIZE=2G
    volumes:
      - ./varnish/:/etc/varnish:delegated
    depends_on:
      - app
      - api
    ports:
      - 80:80